"""
Generate an "anime countdown" SVG card and keep README.md in sync with it.

Reads anime_config.json:
  {
    "title": "One Piece",
    "episode_label": "Episode 1130",
    "next_air_at": "2026-07-13T17:00:00",   # naive local time, in `timezone`
    "timezone": "Asia/Tokyo",
    "recurring_weekly": true                # roll forward 7 days after it airs
  }

Writes:
  - assets/anime-countdown.svg   (the visual card, embedded in README via <img>)
  - README.md                    (fallback text table between markers, for
                                   anyone viewing raw markdown / if the image
                                   fails to load)

A real ticking countdown can't run inside a GitHub README — GitHub strips
<script> tags from rendered markdown. Instead this script is meant to be run
on a schedule by .github/workflows/update-anime-countdown.yml (every 30 min),
so the card is always close to accurate without needing JavaScript.
"""

import json
import os
import sys
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

CONFIG_PATH = "anime_config.json"
SVG_PATH = "assets/anime-countdown.svg"
README_PATH = "README.md"

START_MARKER = "<!-- ANIME-COUNTDOWN-START -->"
END_MARKER = "<!-- ANIME-COUNTDOWN-END -->"


def load_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"{CONFIG_PATH} not found.", file=sys.stderr)
        sys.exit(1)
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def next_air_datetime(cfg):
    tz = ZoneInfo(cfg["timezone"])
    naive = datetime.fromisoformat(cfg["next_air_at"])
    target = naive.replace(tzinfo=tz)
    now = datetime.now(tz)

    if cfg.get("recurring_weekly"):
        while target <= now:
            target += timedelta(days=7)

    return target, now


def format_countdown(delta: timedelta):
    total_seconds = max(int(delta.total_seconds()), 0)
    days, rem = divmod(total_seconds, 86400)
    hours, rem = divmod(rem, 3600)
    minutes, _ = divmod(rem, 60)
    return days, hours, minutes


def build_svg(cfg, target, now, days, hours, minutes):
    aired = target <= now
    week_seconds = 7 * 86400
    if cfg.get("recurring_weekly"):
        elapsed = week_seconds - max(int((target - now).total_seconds()), 0)
        progress = max(0.0, min(1.0, elapsed / week_seconds))
    else:
        progress = 1.0 if aired else 0.0

    bar_width = 440
    bar_fill = round(bar_width * progress)

    status = "ALREADY AIRED — CHECK BACK NEXT WEEK" if aired else "COUNTING DOWN"
    big_line = "00d 00h 00m" if aired else f"{days:02d}d {hours:02d}h {minutes:02d}m"

    title = cfg.get("title", "Untitled")
    episode = cfg.get("episode_label", "")

    return f'''<svg width="500" height="170" viewBox="0 0 500 170" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0d1117"/>
      <stop offset="100%" stop-color="#0a0a0a"/>
    </linearGradient>
  </defs>
  <rect x="1" y="1" width="498" height="168" rx="14" fill="url(#bg)" stroke="#A9FEF7" stroke-width="2"/>

  <text x="30" y="38" font-family="Courier New, monospace" font-size="12" letter-spacing="3" fill="#A9FEF7">
    ANIME COUNTDOWN
  </text>

  <text x="30" y="72" font-family="Courier New, monospace" font-size="22" font-weight="bold" fill="#ffffff">
    {title}
  </text>
  <text x="30" y="94" font-family="Courier New, monospace" font-size="13" fill="#999999">
    {episode}
  </text>

  <text x="30" y="132" font-family="Courier New, monospace" font-size="30" font-weight="bold" fill="#FF6E96">
    {big_line}
  </text>

  <rect x="30" y="148" width="{bar_width}" height="8" rx="4" fill="#1c1c1c"/>
  <rect x="30" y="148" width="{bar_fill}" height="8" rx="4" fill="#A9FEF7"/>

  <text x="470" y="38" font-family="Courier New, monospace" font-size="10" fill="#666666" text-anchor="end">
    {status}
  </text>
</svg>
'''


def update_readme(cfg, target, days, hours, minutes, aired):
    if not os.path.exists(README_PATH):
        print(f"{README_PATH} not found, skipping README update.", file=sys.stderr)
        return

    with open(README_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    if START_MARKER not in content or END_MARKER not in content:
        print(f"Markers {START_MARKER}/{END_MARKER} not found in README.md — skipping.", file=sys.stderr)
        return

    countdown_text = "already aired — check back next week" if aired else f"{days}d {hours}h {minutes}m"
    fallback = (
        f"| **Title** | {cfg.get('title', '')} |\n"
        f"|---|---|\n"
        f"| **Episode** | {cfg.get('episode_label', '')} |\n"
        f"| **Next air (local time)** | {target.strftime('%Y-%m-%d %H:%M %Z')} |\n"
        f"| **Time remaining** | {countdown_text} |\n"
    )

    comment = (
        "<!-- Auto-generated by scripts/update_anime_countdown.py — don't edit by hand. -->\n"
        '<img src="assets/anime-countdown.svg" alt="Anime countdown"/>\n\n'
    )

    before, rest = content.split(START_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    new_content = f"{before}{START_MARKER}\n{comment}{fallback}\n{END_MARKER}{after}"

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(new_content)


def main():
    cfg = load_config()
    target, now = next_air_datetime(cfg)
    delta = target - now
    days, hours, minutes = format_countdown(delta)
    aired = target <= now

    os.makedirs(os.path.dirname(SVG_PATH), exist_ok=True)
    svg = build_svg(cfg, target, now, days, hours, minutes)
    with open(SVG_PATH, "w", encoding="utf-8") as f:
        f.write(svg)

    update_readme(cfg, target, days, hours, minutes, aired)
    print(f"Countdown updated: {days}d {hours}h {minutes}m until {cfg.get('title')} — {cfg.get('episode_label')}")


if __name__ == "__main__":
    main()
